# Generated by Django 4.1.7 on 2023-03-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='pricepricePerHalfLitre',
        ),
        migrations.AddField(
            model_name='product',
            name='pricepricePerLitre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
