# Generated by Django 4.1.7 on 2023-03-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0002_rename_price_product_pricepriceperhalflitre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pricepricePerHalfLitre',
            new_name='pricePerHalfLitre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pricepricePerLitre',
            new_name='pricePerLitre',
        ),
    ]
