# Generated by Django 4.1.7 on 2023-03-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0002_alter_order_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packaging',
            field=models.CharField(choices=[('500ml bottles', '500ml bottles'), ('1L bottles', '1L bottles')], max_length=100, null=True),
        ),
    ]
