# Generated by Django 4.1.7 on 2023-03-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0005_alter_order_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
