# Generated by Django 4.1.7 on 2023-03-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0005_remove_customer_product_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered')], max_length=100, null=True),
        ),
    ]
