# Generated by Django 4.1.7 on 2023-03-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0006_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('fulfilled', 'fulfilled')], max_length=100, null=True),
        ),
    ]
