# Generated by Django 4.1.7 on 2023-03-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0007_alter_orders_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
