# Generated by Django 4.1.7 on 2023-03-21 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0008_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging',
            field=models.CharField(choices=[('500ml bottles', '500ml bottles'), ('1L bottles', '1L bottles')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.IntegerField(default=0, null=True)),
                ('Selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('packaging', models.CharField(choices=[('500ml bottles', '500ml bottles'), ('1L bottles', '1L bottles')], max_length=100, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockManager.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockManager.product')),
            ],
        ),
    ]
