# Generated by Django 4.1.7 on 2023-03-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0009_order_packaging_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Selling_price',
            new_name='selling_price',
        ),
    ]
