# Generated by Django 4.1.7 on 2023-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0009_order_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
