# Generated by Django 4.1.7 on 2023-03-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0012_alter_order_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packaging',
            field=models.CharField(blank=True, choices=[('500ml bottles', '500ml bottles'), ('1L bottles', '1L bottles')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity_in_litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
