# Generated by Django 4.1.7 on 2023-03-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0013_alter_order_packaging_alter_order_quantity_in_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packaging',
            field=models.CharField(blank=True, choices=[('500ml bottles', '500ml bottles'), ('1L bottles', '1L bottles'), ('5L jerry cans', '5L jerry cans'), ('10L jerry cans', '10L jerry cans'), ('20L jerry cans', '20L jerry cans')], max_length=100, null=True),
        ),
    ]
