# Generated by Django 4.1.7 on 2023-03-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManager', '0014_alter_order_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('expense_tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
